<a href="https://colab.research.google.com/github/AmaniAlnabhani/AmaniAlnabhani-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [5]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [6]:
# creating 1 dis array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
a.shape

(4,)

In [10]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [12]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


#Initial Placeholder



In [14]:
# create a new numpy array of zero 4 row 5 col
x= np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
# create numpy array all ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# create array of particular value
z= np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [19]:
# create an identity matrix
a= np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
# create numpy array randoms value
b= np.random.random((3,4))
print(b)


[[0.96668254 0.41108778 0.38766034 0.4645981 ]
 [0.39236735 0.74459125 0.96249991 0.70785678]
 [0.95576515 0.25304407 0.33208137 0.61169318]]


In [22]:
# random int value array within a specific range
c= np.random.randint(10,100,(3,5))
print(c)

[[43 34 46 79 48]
 [46 80 86 60 50]
 [14 51 75 42 40]]


In [24]:
# array of evenly spaced vales --- spacifiying the number of values required
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [26]:
# array of evenly space values --> spacifiying the step
e= np.arange(10,30,5)
print(e)

[10 15 20 25]


In [28]:
# convert list to numpy array
list2=[10,20,30,40,50]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array


In [29]:
c=np.random.randint(10,90,(5,5))
print(c)

[[52 87 12 59 59]
 [51 88 54 29 41]
 [81 20 77 40 32]
 [55 14 31 62 85]
 [75 60 76 22 13]]


In [30]:
# array diemension
print(c.shape)

(5, 5)


In [31]:
# number of diemenstions
print(c.ndim)

2


In [32]:
# checking number of elementin array
print(c.size)

25


In [33]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [34]:
list1 =[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1 + list2)  # concatenate or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [36]:
a= np.random.randint(0,10,(3,3))
b= np.random.randint(10,20,(3,3))
print(a)
print(b)


[[4 6 3]
 [6 4 1]
 [4 6 2]]
[[10 16 17]
 [10 13 19]
 [14 15 12]]


In [37]:
print(a+b)

[[14 22 20]
 [16 17 20]
 [18 21 14]]


In [38]:
print(a-b)
print(a*b)
print(a/b)

[[ -6 -10 -14]
 [ -4  -9 -18]
 [-10  -9 -10]]
[[40 96 51]
 [60 52 19]
 [56 90 24]]
[[0.4        0.375      0.17647059]
 [0.6        0.30769231 0.05263158]
 [0.28571429 0.4        0.16666667]]


In [39]:
print(np.add(a,b))

[[14 22 20]
 [16 17 20]
 [18 21 14]]


In [40]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ -6 -10 -14]
 [ -4  -9 -18]
 [-10  -9 -10]]
[[40 96 51]
 [60 52 19]
 [56 90 24]]
[[0.4        0.375      0.17647059]
 [0.6        0.30769231 0.05263158]
 [0.28571429 0.4        0.16666667]]


Array Manipulation

In [41]:
array =np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 0 0]
 [1 8 0]]
(2, 3)


In [43]:
3 #transpose change shape of array
trans =np.transpose(array)
print(trans)
print(trans.shape)

[[5 1]
 [0 8]
 [0 0]]
(3, 2)


In [44]:
array =np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 0 0]
 [4 0 9]]
(2, 3)


In [45]:
trans2 =array.T
print(trans2)
print(trans2.shape)

[[8 4]
 [0 0]
 [0 9]]
(3, 2)


In [48]:
# reshaping array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 2 2]
 [2 4 6]]
(2, 3)


In [50]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[0 2]
 [2 2]
 [4 6]]
(3, 2)
